---
runtime: python37

handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html
    secure: always
    redirect_http_response_code: 302

  - url: /(.*)
    static_files: www/\1
    upload: www/(.*)
    secure: always
    redirect_http_response_code: 302
